### ISSUE TITLE
Missing server_config.py

### ISSUE THREAD

**Issue by TJKNL** [d2hydro/fews-bokeh#2]
Beste, server_config.py lijkt te missen voor de aa en maas implementatie. Het vervangen met config.py werkt voor sommige variabelen maar niet voor alles. NOW bijvoorbeeld mist dan nog.

Twan - Data Scientist @ Aa en Maas

**Comment by d2hydro** [comment]
Klopt, want de variabelen die daar staan zijn per server verschillend. Je moet hem dus zelf aanmaken. Zie voor een complete handleiding: https://docs.google.com/document/d/1-rolgo7hXHNKsVfZtKSES0a-hzpQ6_eYIWQ_qB6lXjo

**Comment by TJKNL** [comment]
Top heb hem. Bedankt!
